version: '2'
services:
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    env_file: .env
    environment:
      DEBUG: 'true'

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - app
    links:
      - app:app
